---
- hosts: csr

  tasks:
          - name: Show version
            ios_command:
                    commands: show run
            register: version
          - name: print versions
            copy:
              content: "{{version.stdout[0]}}\n\r"
              dest: ~/Cisco-ansible-backup/{{inventory_hostname}}-cfg.txt
            
