---
- hosts: all

  tasks:
          - name: Show version
            ios_command:
                    commands: show run
            register: version
          - name: print versions
            copy:
              content: "{{version.stdout[0]}}\n\r"
              dest: "{{ playbook_dir }}/{{inventory_hostname}}-cfg.txt
            
